[workspace]

members = [
    "mongodb-enforcement",
    "mongodb-enforcement/example-project",
    "mongodb-migrate",
    "policy-lang",
    "static-checker",
    "cli",
    "bench/postfriend",
    "web-demo",
    "web-demo/wasm-validator"
]

exclude = ["case-studies/bibifi"]
