[package]
name = "web-demo"
version = "0.1.0"
authors = ["John Renner <john@jrenner.net>"]
edition = "2018"


[dependencies]
rocket="0.5.0-rc.1"
static-checker={path="../static-checker", features=["naive_smt"]}
