[package]
name = "wasm-validator"
version = "0.1.0"
authors = ["John Renner <john@jrenner.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
policy-lang = {path = "../../policy-lang"}
